version: "3.8"

services:
  frontend:
    build: ../frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - cbu-net

  backend:
    build: ../backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ../DevOps/config/application.properties:/backend/src/main/resources/application.properties
      - ../DevOps/config/cbumanage.json:/backend/src/main/resources/cbumanage.json
    depends_on:
      - redis
    networks:
      - cbu-net

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - cbu-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env.dev
      - .env
    depends_on:
      - frontend
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - cbu-net

networks:
  cbu-net:
    driver: bridge
