version: "3.8"

services:
  backend:
    build: ../backend
    container_name: backend
    image: souljump/cbumanage
    expose:
      - "8080"
    env_file:
      - .env.dev
    volumes:
      - ../DevOps/config/application.properties:/backend/src/main/resources/application.properties
      - ../DevOps/config/cbumanage.json:/backend/src/main/resources/cbumanage.json
    depends_on:
      - redis

  nginx:
    build:
      context: ../
      dockerfile: DevOps/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env.dev    # dev 서버
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - cbu-net
networks:
  cbu-net:
    driver: bridge
