name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # frontend 디렉토리의 변경사항만 감지

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... 프론트엔드 관련 배포 스텝들